### ISSUE TITLE
consolidate to a single vendor list

### ISSUE THREAD

**Issue by katie-ta** [katie-ta/Cookie-Glasses#42]
- display a list of the vendors that are actively processing a user's data based on the allowed purposes
- show which purposes (consent and legit interest) are used by each vendor

**Comment by charles-tan** [comment]
related PR: https://github.com/katie-ta/Cookie-Glasses/pull/43 

A lot of the work for fixing the logic is included in https://github.com/katie-ta/Cookie-Glasses/pull/43, but we still need to fix the frontend and fix a few remaining things in the backend – removing old artifacts and filtering the merged list.

**Comment by katie-ta** [comment]
fixed in #44
